apiVersion: v2
name: spring-boot-example-health-check
version: 0.0.1-SNAPSHOT
description: A Helm chart to build and deploy Spring Boot application with Health Checks
keywords:
  - runtimes
  - spring-boot
icon: https://avatars.githubusercontent.com/u/558276?s=400&u=19efc68c74844b2e092698a8a7a752921edcdc19&v=4
dependencies:
  - name: spring-boot-example-app
    version: 0.0.3
    repository: http://snowdrop.github.io/helm
